---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/gallery
  label: Gallery
  create: documents
  match: "**/*inc.md"
  templates:
  - artwork
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*inc.md"
  exclude: "**/*exc.md"
  templates:
  - artwork
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
