---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/homepage images inc.md
  label: Homepage Images
- type: directory
  path: content/about
  label: About
  create: none
  match: "**/*inc.md"
- type: directory
  path: content/gallery
  label: Gallery Category Photos
  create: none
  match: "**/*inc.md"
- type: directory
  path: content/gallery/board
  label: Board Artwork
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - artwork
- type: directory
  path: content/gallery/canvas
  label: Canvas Artwork
  create: documents
  match: "**/*"
  exclude: "*_index.md"
  templates:
  - canvas-artwork
- type: directory
  path: content/gallery/paper
  label: Paper Artwork
  create: documents
  match: "**/*"
  exclude: "*_index.md"
  templates:
  - paper-artwork
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.51
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.51
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.51'
