---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/homepage images inc.md
  label: Homepage Images
- type: directory
  path: content/about
  label: About
  create: none
  match: "**/*inc.md"
- type: directory
  path: content/gallery/board
  label: Board Artwork
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - artwork
- type: directory
  path: content/gallery
  label: Gallery Category Photos
  create: none
  match: "**/*inc.md"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
